#!/bin/bash
screenname=$(xrandr | grep " connected" | cut -f1 -d" ")
current=$(xrandr --verbose | grep -m 1 -i brightness | cut -f2 -d ' ')
current=$(($((`echo $current | cut -f1 -d'.'`*100))+$((`echo $current | cut -f2 -d'.'`))))
step=10
if test $# -gt 0
then
	#CHECK FOR FLAG - DEFAULT = -set
	test=`echo $1 | egrep '\-'`
	if test $? -ne 0
	then
		flag="set"
	else
		flag=`echo $1 | cut -f2 -d-`
		shift 1
	fi
	case $flag in
		set)		
			if test $1 -gt 100
			then
				brightness_level=1
			elif test $1 -lt 0
			then
				brightness_level=0
			else
				brightness_level="$(($1/100)).$(($1%100))"
			fi
			xrandr --output $screenname --brightness $brightness_level;
		;;
		inc)
			if test $# -gt 0
			then
				current=$((current+$1))
			else
				current=$((current+$step))
			fi
			brightness -set $current
		;;	
		dec)
			if test $# -gt 0
			then
				current=$((current-$1))
			else
				current=$((current-$step))
			fi
			brightness -set $current
		;;	
		current)
			echo $current
		;;
		*)
			echo "Not a valid flag"
		;;
	esac
else
	echo "The script brightness needs more than one argument"
fi
