#!/bin/bash
# Wallpaper (feh)
sudo apt-get install feh
# NERDTree VIM
git clone https://github.com/preservim/nerdtree.git ~/.vim/pack/vendor/start/nerdtree
vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q
